# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  MacOS-Flutter-Stable:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable Flutter Desktop support
        run: flutter config --enable-macos-desktop

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./beta_test_drive/

      - name: Run tests
        run: flutter test integration_test/app_test.dart -d macos -j 1 --test-randomize-ordering-seed random --verbose -r expanded
        working-directory: ./beta_test_drive/

  Windows-Flutter-Stable:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable Flutter Desktop support
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./beta_test_drive/

      - name: Run tests
        run: flutter test integration_test/app_test.dart -d windows -j 1 --test-randomize-ordering-seed random -r expanded
        working-directory: ./beta_test_drive/